"""empty message

Revision ID: 35811a3c69fe
Revises: db52c4ca309a
Create Date: 2022-02-11 15:29:02.493262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35811a3c69fe'
down_revision = 'db52c4ca309a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collaborators')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborators',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], name='collaborators_project_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='collaborators_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'project_id', name='collaborators_pkey')
    )
    # ### end Alembic commands ###
