"""empty message

Revision ID: db52c4ca309a
Revises: f0a0b4d61771
Create Date: 2022-02-04 13:09:13.538641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db52c4ca309a'
down_revision = 'f0a0b4d61771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborators',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.drop_table('collaborator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborator',
    sa.Column('collaborator_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], name='collaborator_project_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='collaborator_user_id_fkey'),
    sa.PrimaryKeyConstraint('collaborator_id', name='collaborator_pkey')
    )
    op.drop_table('collaborators')
    # ### end Alembic commands ###
